apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  labels:
    name: back
spec:
  selector:
    matchLabels:
      name: back
  replicas: 2
  template:
    metadata:
      labels:
        name: back
    spec:
      containers:
      - name: back1
        image: back1:6
        ports:
          - containerPort: 9000
      - name: back2
        image: back2:6
        ports:
          - containerPort: 9001
