apiVersion: v1
kind: Pod
metadata:
  name: front1-pod
  labels:
    name: front1
    component: frontend
spec:
  containers:
    - name: front1
      image: front1:6
      ports:
        - name: http
          protocol: TCP
          port: 9080
          targetPort: 80

