apiVersion: v1
kind: Service
metadata:
  name: back2
  namespace: automation-t3
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    name: back2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
