apiVersion: v1
kind: Service
metadata:
  name: back1
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    name: back1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
